spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile},youzan
    include:

server:
  port: 7001


endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


#cas接入参数
cas:
  projectName: apollo-portal
  secret: be42efc6-f01f-4acc-84a2-021e6bc49101

#开放平台接入参数
openapi:
  appsecret: d40a15b5-024c-410e-bb6f-97cadda77148
