spring:
  application:
    name: apollo-portal
  profiles:
    active: ${apollo_profile},youzan

server:
  port: 7001


endpoints:
  health:
    sensitive: false
management:
  security:
    enabled: false
  health:
    status:
      order: DOWN, OUT_OF_SERVICE, UNKNOWN, UP 


#cas接入参数
cas:
  projectName: apollo-portal
  secret: be42efc6-f01f-4acc-84a2-021e6bc49101

security:
  ignored: /**